import type { ExplainerMeta, ExplainerStep, FailureScenario } from "./types";
import { brandContext } from "./brand-context";

export const migrationFailureScenarios: FailureScenario[] = [
  { id: "compatibility-gap", sceneId: "limits", label: "Compatibilidad no comprobada", summary: "El destino no cumple una condición de la VM o del host.", detail: "CPU, versión de hardware virtual, dispositivos conectados, redes, políticas y HCL pueden impedir una migración aunque ambos hosts parezcan disponibles.", limitation: "La animación no consulta el Compatibility Guide ni calcula una matriz de compatibilidad.", affectedNodes: ["inventory", "compatibility"], deadNodeIds: ["compatibility"] },
  { id: "vMotion-network", sceneId: "limits", label: "Red de migración degradada", summary: "La transferencia no mantiene la ventana planificada.", detail: "vMotion necesita una red preparada y suficiente ancho de banda; latencia, pérdida, MTU o congestión pueden alargar la convergencia o provocar un fallo.", limitation: "No se capturan paquetes ni se mide throughput real.", affectedNodes: ["migration-net", "destination"], deadNodeIds: ["migration-net"] },
  { id: "storage-path", sceneId: "limits", label: "Destino sin storage válido", summary: "La VM llega a un host que no puede presentar su datastore.", detail: "Una migración de cómputo, de storage o combinada tiene requisitos diferentes. Datastore, paths, permisos y políticas deben existir en el destino.", limitation: "No se valida zoning, mapping, multipath ni una Storage Policy real.", affectedNodes: ["storage", "destination"], deadNodeIds: ["storage"] },
  { id: "rollback-untested", sceneId: "limits", label: "Rollback no probado", summary: "La reversión existe en el documento, pero no está demostrada.", detail: "Un backup, snapshot o copia no equivale a un rollback operativo. Hay que definir punto de retorno, dependencias, ventana y aceptación del servicio.", limitation: "La demo no ejecuta una reversión ni valida la aplicación.", affectedNodes: ["rollback", "service"], deadNodeIds: ["rollback"] },
];

export const migrationMeta: ExplainerMeta = {
  chip: "Continuidad · Migración",
  title: "Cómo migrar una plataforma sin detener el negocio",
  tagline: "Una guía visual para pasar de inventario y compatibilidad a oleadas, validación y rollback con el riesgo explícito.",
  brandContext: brandContext.migration,
  storyboardDoc: "docs/examples/migration/storyboard.md",
  technicalValidationDoc: "docs/ai-context/migration-technical-validation.md",
  technicalReview: {
    lastReviewedAt: "2026-08-05",
    scope: "Patrón conceptual revisado con vSphere/vMotion 8.x, PowerCLI Move-VM, Broadcom Compatibility Guide, Veeam Backup & Replication 13 y patrones IBM/Lenovo de storage y cómputo; confirmar release, licencia, HCL, red, storage, aplicación y ventana del cliente.",
    sources: [
      { id: "broadcom-vmotion", title: "Broadcom PowerCLI Move-VM reference", url: "https://developer.broadcom.com/powercli/latest/vmware.vimautomation.core/commands/move-vm/", accessedAt: "2026-08-05" },
      { id: "broadcom-compatibility", title: "VMware by Broadcom Compatibility Guide", url: "https://compatibilityguide.broadcom.com/", accessedAt: "2026-08-05" },
      { id: "broadcom-migration-faults", title: "vSphere MigrationFault reference", url: "https://developer.broadcom.com/xapis/vsphere-web-services-api/latest/vim.fault.MigrationFault.html", accessedAt: "2026-08-05" },
      { id: "veeam-overview", title: "Veeam Backup & Replication overview", url: "https://helpcenter.veeam.com/docs/vbr/userguide/overview.html", accessedAt: "2026-08-05" },
      { id: "ibm-lpm", title: "IBM PowerVM Live Partition Mobility", url: "https://www.ibm.com/docs/en/power10/9028-21B?topic=mobility-benefits-partition", accessedAt: "2026-08-05" },
    ],
  },
  reviewStatus: "pending",
  failureScenarios: migrationFailureScenarios,
};

export const migrationSteps: ExplainerStep[] = [
  { id: "discovery", tag: "01 — DESCUBRIMIENTO", title: "Migrar empieza por conocer dependencias, no por mover VMs", paragraphs: ["El inventario debe incluir workloads, hosts, datastores, redes, identidad, backup, ventanas y responsables. Una carga que parece aislada puede depender de DNS, SAN, firewall o una integración externa.", "En PowerVM, VMware o servidores físicos, la movilidad disponible y sus requisitos cambian por plataforma. El alcance debe separar migración de cómputo, storage, sistema operativo y aplicación."], businessImpact: "El cliente obtiene una lista de decisiones y dependencias antes de comprometer una ventana de cambio.", sceneId: "discovery", caption: "Workloads → dependencias → inventario → plan de oleadas", sourceIds: ["broadcom-vmotion", "ibm-lpm"] },
  { id: "compatibility", tag: "02 — COMPATIBILIDAD", title: "El destino debe ser compatible y estar preparado", paragraphs: ["vMotion y movimientos equivalentes no son magia: CPU, hardware virtual, dispositivos, redes, permisos y storage deben cumplir las condiciones de la plataforma. La Compatibility Guide y la matriz del fabricante son parte del diseño.", "Una validación madura prueba primero una carga representativa. Si el destino no comparte un datastore o una política, puede requerir Storage vMotion, replicación, backup/restore u otra estrategia."], businessImpact: "La compatibilidad deja de ser una sorpresa durante el cambio y se convierte en una puerta de entrada medible.", sceneId: "compatibility", caption: "Matriz de compatibilidad + red + storage + permisos", sourceIds: ["broadcom-compatibility", "broadcom-migration-faults"] },
  { id: "waves", tag: "03 — OLEADAS", title: "Las oleadas reducen el radio de impacto", paragraphs: ["Una oleada puede comenzar con una carga de baja criticidad, continuar con servicios relacionados y dejar las dependencias críticas para cuando ya existe evidencia. El orden importa más que la velocidad de una sola migración.", "Durante la ejecución se conserva un punto de observación: estado del host, latencia, paths, sesiones, jobs de backup y salud de la aplicación. Migrar no termina cuando la consola muestra una marca verde."], businessImpact: "El equipo puede detenerse entre oleadas sin convertir un error local en una indisponibilidad general.", sceneId: "waves", caption: "Piloto → oleada controlada → dependencias → carga crítica", sourceIds: ["broadcom-vmotion", "veeam-overview"] },
  { id: "validation", tag: "04 — VALIDACIÓN", title: "La aceptación es del servicio, no solo de la infraestructura", paragraphs: ["Después del movimiento se valida conectividad, rendimiento, identidad, DNS, storage, monitoreo, backup y comportamiento de la aplicación. La VM encendida es una condición necesaria, no una prueba completa.", "El criterio debe quedar acordado antes del cambio: quién prueba, qué métricas se esperan, cuánto tiempo se observa y qué evento dispara el rollback."], businessImpact: "El cliente recibe evidencia de que el servicio funciona en el destino y no solo de que el job terminó.", sceneId: "validation", caption: "Infraestructura → dependencias → aplicación → aceptación", sourceIds: ["broadcom-migration-faults", "veeam-overview"] },
  { id: "limits", tag: "05 — LÍMITES", title: "Sin rollback probado, la migración todavía tiene riesgo abierto", paragraphs: ["Activa un fallo para recorrer compatibilidad, red de migración, storage y reversión. Un backup puede ser una red de seguridad, pero su valor depende de retención, aislamiento, tiempo de restore y prueba real.", "La animación no calcula el downtime, no certifica una licencia ni garantiza que una aplicación sea compatible. Es un mapa para preparar el runbook y la aceptación con el cliente."], businessImpact: "La conversación pasa de ‘movemos y vemos’ a ‘sabemos cómo detectar, detener y volver atrás’. ", sceneId: "limits", caption: "Activa fallos para descubrir qué condición aún no está demostrada", sourceIds: ["broadcom-compatibility", "broadcom-migration-faults", "veeam-overview"] },
];
