import type { ExplainerMeta, ExplainerStep, FailureScenario } from "./types";
import { brandContext } from "./brand-context";

export const implementationLifecycleFailureScenarios: FailureScenario[] = [
  { id: "prerequisites", sceneId: "limits", label: "Prerrequisitos incompletos", summary: "La instalación empieza sin una condición crítica confirmada.", detail: "Rack, energía, puertos, direccionamiento, HCL, licencias, ventanas y responsables son dependencias del camino. Si falta una, la tarea puede bloquearse o crear retrabajo.", limitation: "La animación no audita el sitio ni sustituye un site survey.", affectedNodes: ["prerequisites", "rack"], deadNodeIds: ["prerequisites"] },
  { id: "integration", sceneId: "limits", label: "Integración parcial", summary: "Cada componente funciona aislado, pero el servicio no cruza las capas.", detail: "LAN, SAN, storage, hipervisor, seguridad, backup y aplicación deben probarse como una cadena. Un ‘OK’ local no demuestra integración.", limitation: "La demo no ejecuta conectividad, zoning, jobs ni pruebas funcionales.", affectedNodes: ["integration", "service"], deadNodeIds: ["integration"] },
  { id: "acceptance", sceneId: "limits", label: "Criterio de aceptación ambiguo", summary: "El proyecto termina sin evidencia compartida.", detail: "Si no se acuerdan métricas, pruebas, responsables y formato de acta, una instalación técnicamente correcta puede seguir siendo percibida como incompleta.", limitation: "La animación no genera un acta ni firma de aceptación.", affectedNodes: ["acceptance", "documentation"], deadNodeIds: ["acceptance"] },
  { id: "knowledge-transfer", sceneId: "limits", label: "Operación sin transferencia", summary: "El cliente recibe una plataforma, pero no un sistema operable.", detail: "Documentación, capacitación, credenciales, monitoreo, procedimientos y soporte posterior forman parte del resultado, especialmente en cambios de equipo.", limitation: "La demo no mide adopción ni disponibilidad del soporte.", affectedNodes: ["documentation", "operations"], deadNodeIds: ["documentation"] },
];

export const implementationLifecycleMeta: ExplainerMeta = {
  chip: "Servicios · Implementación",
  title: "Del rack a la aceptación: cómo se implementa una plataforma empresarial",
  tagline: "Una vista de extremo a extremo para entender descubrimiento, instalación, integración, pruebas, documentación y adopción.",
  brandContext: brandContext.implementationLifecycle,
  storyboardDoc: "docs/examples/implementation-lifecycle/storyboard.md",
  technicalValidationDoc: "docs/ai-context/implementation-lifecycle-technical-validation.md",
  technicalReview: {
    lastReviewedAt: "2026-08-05",
    scope: "Patrón de proceso derivado del resumen sanitizado de proyectos de CORESOLUTIONS y contrastado con guías oficiales de Aruba, IBM, Veeam y Broadcom; validar alcance, HCL, licencias, ventanas, responsables y criterios de aceptación por proyecto.",
    sources: [
      { id: "project-patterns", title: "Patrones sanitizados de proyectos CORESOLUTIONS", url: "https://github.com/Jaywrkr/COREEXPLAINER/blob/claude/coresolutions-explainer-setup-cvc6uk/docs/product/coresolutions-project-patterns.md", accessedAt: "2026-08-05" },
      { id: "aruba-deploy", title: "Aruba validated data center deployment", url: "https://www.arubanetworks.com/techdocs/VSG/docs/050-dc-deploy/Media/PDF/Aruba_VSG_Data-Center-Deploy.pdf", accessedAt: "2026-08-05" },
      { id: "ibm-mapping", title: "IBM FlashSystem host mapping", url: "https://www.ibm.com/docs/en/flashsystem-5x00/9.1.0?topic=hosts-host-mapping", accessedAt: "2026-08-05" },
      { id: "veeam-architecture", title: "Veeam backup infrastructure", url: "https://helpcenter.veeam.com/docs/vbr/userguide/backup_architecture.html", accessedAt: "2026-08-05" },
      { id: "broadcom-compatibility", title: "VMware by Broadcom Compatibility Guide", url: "https://compatibilityguide.broadcom.com/", accessedAt: "2026-08-05" },
      { id: "checkpoint-install", title: "Check Point ClusterXL installation", url: "https://sc1.checkpoint.com/documents/R82/WebAdminGuides/EN/CP_R82_Installation_and_Upgrade_Guide/Content/Topics-IUG/Installing-ClusterXL-Cluster.htm", accessedAt: "2026-08-05" },
    ],
  },
  reviewStatus: "pending",
  failureScenarios: implementationLifecycleFailureScenarios,
};

export const implementationLifecycleSteps: ExplainerStep[] = [
  { id: "discovery", tag: "01 — DESCUBRIMIENTO", title: "Un proyecto empieza antes de abrir una caja", paragraphs: ["Se levantan objetivos, inventario, dependencias, sitio, energía, rack, puertos, direccionamiento, HCL, licencias, ventanas y criterios de éxito. El proyecto real se construye con esas restricciones.", "El resultado es una línea base y un plan de trabajo: qué se implementa, qué queda fuera y qué decisión necesita el cliente antes de continuar."], businessImpact: "El cliente puede validar el alcance antes de que el equipo técnico convierta supuestos en tareas.", sceneId: "discovery", caption: "Objetivo → inventario → dependencias → alcance aprobado", sourceIds: ["project-patterns", "broadcom-compatibility"] },
  { id: "rack", tag: "02 — INSTALACIÓN", title: "La capa física condiciona todo lo que viene después", paragraphs: ["Rack, PDU, cableado, etiquetas, módulos, discos, memoria, adaptadores, gestión remota y firmware deben quedar identificados. Una instalación ordenada reduce errores de integración y soporte.", "Los fabricantes publican guías y compatibilidades por familia. El patrón no asume que un modelo, firmware o HCL sea intercambiable con otro."], businessImpact: "El cliente obtiene trazabilidad del activo y una base física preparada para operar.", sceneId: "rack", caption: "Rack → energía → cableado → gestión → firmware", sourceIds: ["aruba-deploy", "broadcom-compatibility"] },
  { id: "integration", tag: "03 — INTEGRACIÓN", title: "El valor aparece cuando las capas cruzan el diagrama", paragraphs: ["Se configuran RAID/pools, LUNs, VLANs, routing, SAN, multipath, hipervisor, repositorios, seguridad y políticas. Después se conectan hosts, storage, backup y aplicaciones.", "Cada capa tiene una prueba local, pero el servicio necesita una prueba de extremo a extremo: usuario, red, compute, storage, seguridad, backup y aplicación."], businessImpact: "Los responsables pueden localizar el punto de fallo sin convertir cada incidencia en una discusión entre fabricantes.", sceneId: "integration", caption: "Compute + LAN + SAN + security + backup → servicio", sourceIds: ["ibm-mapping", "veeam-architecture", "checkpoint-install"] },
  { id: "acceptance", tag: "04 — PRUEBAS Y CIERRE", title: "La entrega incluye evidencia y capacidad de operar", paragraphs: ["Se prueban conectividad, reconocimiento de volúmenes, alta disponibilidad, replicación, backup, restore, rendimiento, failover y aceptación de aplicación según el alcance.", "El cierre debe dejar diagramas, configuración, actas, pendientes, capacitación y un contacto de soporte. La documentación no es decoración: es parte del control operativo."], businessImpact: "El cliente sabe qué se probó, qué queda pendiente y cómo mantener el resultado después de la implementación.", sceneId: "acceptance", caption: "Prueba → evidencia → documentación → transferencia", sourceIds: ["project-patterns", "veeam-architecture", "checkpoint-install"] },
  { id: "limits", tag: "05 — LÍMITES", title: "Un proyecto maduro hace visibles los riesgos antes del cierre", paragraphs: ["Activa fallos de prerrequisitos, integración, aceptación o documentación. El objetivo no es simular una instalación real, sino descubrir qué condición todavía depende de una conversación o prueba.", "La animación no reemplaza site survey, HCL, sizing, licenciamiento, comandos, pruebas de rendimiento ni un acta firmada. Es una vista común para cliente, preventa, ingeniería y operación."], businessImpact: "El trabajo de CORESOLUTIONS se explica como un ciclo completo de adopción, no como una lista de tareas aisladas.", sceneId: "limits", caption: "Activa fallos para descubrir el riesgo abierto antes del cierre", sourceIds: ["project-patterns", "aruba-deploy", "ibm-mapping", "veeam-architecture"] },
];
