import type { TechnicalAuthorityProfile } from "./types";

/**
 * Per-topic authority matrix. It deliberately names the evidence that must
 * govern a topic; brand context alone is never treated as compatibility proof.
 */
export const technicalAuthorityProfiles: Record<string, TechnicalAuthorityProfile> = {
  vcf: { owner: "Broadcom / VMware", equipmentClass: "platform", scope: "VCF release, supported components and platform dependencies", requiredEvidence: [{ sourceId: "vcf-platform", control: "platform components" }, { sourceId: "vcf-91-faq", control: "release scope" }, { sourceId: "vcf-networking", control: "networking dependency" }], requiredRuleFamilies: ["release", "compatibility", "network", "storage", "licensing"] },
  "vsphere-ha": { owner: "Broadcom / VMware", equipmentClass: "hypervisor", scope: "vSphere HA admission, restart and failover conditions", requiredEvidence: [{ sourceId: "vsphere-ha-restart", control: "restart behavior" }], requiredRuleFamilies: ["release", "cluster", "admission-control", "storage", "network"] },
  vsan: { owner: "Broadcom / VMware", equipmentClass: "storage", scope: "vSAN availability, storage policy and host participation", requiredEvidence: [{ sourceId: "vsan-reduced-availability", control: "availability behavior" }], requiredRuleFamilies: ["release", "hcl", "storage-policy", "network", "capacity"] },
  nsx: { owner: "Broadcom / VMware", equipmentClass: "network", scope: "NSX logical networking, transport and enforcement", requiredEvidence: [{ sourceId: "nsx-firewall-well-architected", control: "firewall architecture" }], requiredRuleFamilies: ["release", "underlay", "overlay", "routing", "security-policy"] },
  "zero-trust": { owner: "NIST", equipmentClass: "standard", scope: "Zero Trust architecture principles and scope", requiredEvidence: [{ sourceId: "nist-800-207", control: "architecture standard" }], requiredRuleFamilies: ["identity", "policy", "telemetry", "segmentation"] },
  kubernetes: { owner: "Kubernetes", equipmentClass: "platform", scope: "Kubernetes control plane, workloads and cluster dependencies", requiredEvidence: [{ sourceId: "k8s-architecture", control: "cluster architecture" }], requiredRuleFamilies: ["release", "cni", "csi", "runtime", "availability"] },
  observability: { owner: "OpenTelemetry", equipmentClass: "observability", scope: "OpenTelemetry signals, context and collector pipeline", requiredEvidence: [{ sourceId: "otel-what", control: "signal model" }, { sourceId: "otel-collector", control: "collector pipeline" }], requiredRuleFamilies: ["instrumentation", "context", "pipeline", "retention", "access"] },
  "backup-dr": { owner: "Veeam", equipmentClass: "backup", scope: "Backup architecture, recovery objectives and protected repositories", requiredEvidence: [{ sourceId: "veeam-architecture", control: "backup architecture" }, { sourceId: "veeam-immutability", control: "immutability" }, { sourceId: "veeam-vsphere", control: "platform support" }], requiredRuleFamilies: ["version", "platform-support", "repository", "immutability", "restore-testing"] },
  "ransomware-resilience": { owner: "CISA", equipmentClass: "standard", scope: "Ransomware resilience and recovery guidance", requiredEvidence: [{ sourceId: "cisa-guide", control: "resilience guidance" }], requiredRuleFamilies: ["identity", "segmentation", "backup", "recovery", "incident-response"] },
  "san-storage": { owner: "IBM", equipmentClass: "storage", scope: "FlashSystem host attachment, SAN and volume mapping", requiredEvidence: [{ sourceId: "ibm-host-attachment", control: "host attachment" }], requiredRuleFamilies: ["hcl", "firmware", "zoning", "multipath", "mapping"] },
  "veeam-protection": { owner: "Veeam", equipmentClass: "backup", scope: "Veeam protection architecture and recovery", requiredEvidence: [{ sourceId: "veeam-overview", control: "protection architecture" }], requiredRuleFamilies: ["version", "platform-support", "repository", "recovery", "immutability"] },
  "active-active-dc": { owner: "IBM", equipmentClass: "storage", scope: "IBM high availability across independent domains", requiredEvidence: [{ sourceId: "ibm-ha", control: "high availability policy" }], requiredRuleFamilies: ["topology", "replication", "quorum", "application-consistency", "recovery"] },
  "lan-san": { owner: "HPE Aruba Networking", equipmentClass: "network", scope: "Aruba LAN/SAN design and data center connectivity", requiredEvidence: [{ sourceId: "aruba-design", control: "network design" }], requiredRuleFamilies: ["hardware", "firmware", "vlan", "san", "redundancy"] },
  "nas-private-cloud": { owner: "Synology", equipmentClass: "storage", scope: "Synology NAS and private cloud service constraints", requiredEvidence: [{ sourceId: "synology-files", control: "file services" }], requiredRuleFamilies: ["model", "dsm-version", "capacity", "network", "backup"] },
  migration: { owner: "Broadcom / VMware", equipmentClass: "hypervisor", scope: "Workload migration prerequisites and vMotion constraints", requiredEvidence: [{ sourceId: "broadcom-vmotion", control: "migration requirements" }], requiredRuleFamilies: ["version", "licensing", "network", "storage", "compatibility"] },
  "checkpoint-ha": { owner: "Check Point", equipmentClass: "security", scope: "ClusterXL high availability and member compatibility", requiredEvidence: [{ sourceId: "checkpoint-clusterxl", control: "cluster behavior" }], requiredRuleFamilies: ["version", "member-compatibility", "interfaces", "policy", "failover"] },
  sdwan: { owner: "HPE Aruba Networking", equipmentClass: "network", scope: "Aruba SD-WAN orchestration and branch connectivity", requiredEvidence: [{ sourceId: "aruba-orchestrator", control: "orchestration" }], requiredRuleFamilies: ["hardware", "software-release", "underlay", "routing", "policy"] },
  "power-aix": { owner: "IBM", equipmentClass: "platform", scope: "IBM Power and AIX mobility constraints", requiredEvidence: [{ sourceId: "ibm-lpm", control: "live partition mobility" }], requiredRuleFamilies: ["power-firmware", "aix-version", "hmc", "storage", "network"] },
  "implementation-lifecycle": { owner: "Broadcom / VMware", equipmentClass: "process", scope: "Implementation prerequisites and manufacturer compatibility checks", requiredEvidence: [{ sourceId: "broadcom-compatibility", control: "hardware compatibility" }, { sourceId: "ibm-mapping", control: "storage mapping", owner: "IBM" }, { sourceId: "veeam-architecture", control: "backup architecture", owner: "Veeam" }], requiredRuleFamilies: ["inventory", "hcl", "firmware", "network", "acceptance"] },
  instana: { owner: "IBM", equipmentClass: "observability", scope: "IBM Instana deployment, coverage and investigation", requiredEvidence: [{ sourceId: "instana-capabilities", control: "product capabilities" }, { sourceId: "instana-deployment", control: "deployment model" }], requiredRuleFamilies: ["edition", "agent-coverage", "permissions", "retention", "data-residency"] },
  turbonomic: { owner: "IBM", equipmentClass: "observability", scope: "IBM Turbonomic targets, recommendations and automation governance", requiredEvidence: [{ sourceId: "turb-targets", control: "target configuration" }, { sourceId: "turb-workflow", control: "automation workflow" }], requiredRuleFamilies: ["version", "targets", "permissions", "constraints", "automation"] },
  webmethods: { owner: "IBM", equipmentClass: "integration", scope: "IBM webMethods hybrid integration and interoperability", requiredEvidence: [{ sourceId: "wm-interoperability", control: "supported interoperability" }, { sourceId: "wm-architecture", control: "hybrid architecture" }], requiredRuleFamilies: ["version", "interoperability", "connectivity", "identity", "runtime"] },
};
