import type { GuidedScenarioStep } from "./types";

/**
 * Authored checkpoints for the VCF reference explainer. Keep each phase
 * evidence-led and conditional: this is a teaching path, not a production
 * runbook or an availability guarantee.
 */
export const vcfGuidedSteps: Record<string, GuidedScenarioStep[]> = {
  "host-failure": [
    {
      id: "observe",
      kind: "observe",
      title: "Confirma la perdida del host",
      instruction: "Distingue una alerta de disponibilidad del host de una interrupcion confirmada del servicio.",
      evidence: "host1 aparece como no disponible; la escena no afirma que las VMs ya se hayan recuperado.",
      expected: "Describe el sintoma y separa el componente fallido de las cargas que todavia deben comprobarse.",
      focusNodeIds: ["host1"],
      sourceIds: ["vsphere-ha-restart"],
    },
    {
      id: "diagnose",
      kind: "diagnose",
      title: "Comprueba las condiciones de HA",
      instruction: "Relaciona el host con el storage y la capacidad restante antes de concluir que HA puede reiniciar una VM.",
      evidence: "El camino conceptual pasa por vCenter, los hosts restantes y el datastore vSAN.",
      expected: "Formula una hipotesis comprobable basada en capacidad, storage visible y politicas compatibles.",
      focusNodeIds: ["host1", "host2", "host3", "vsan", "vcenter"],
      sourceIds: ["vsphere-ha-restart", "vsphere-ha-capacity", "vsan-datastore"],
      decision: {
        question: "Que conjunto de condiciones debes comprobar antes de atribuir el reinicio a HA?",
        options: [
          {
            id: "capacity-storage-policy",
            label: "Capacidad, storage visible y politicas compatibles",
            feedback: "Es la hipotesis mas completa: HA puede intentar reiniciar VMs protegidas solo si esas condiciones se cumplen en el entorno objetivo.",
            outcome: "recommended",
            focusNodeIds: ["host2", "host3", "vsan"],
          },
          {
            id: "vmotion-only",
            label: "Que la red de vMotion siga activa",
            feedback: "Es evidencia insuficiente. Una falla de host y un reinicio de HA no son equivalentes a una migracion en vivo.",
            outcome: "incomplete",
            focusNodeIds: ["host1", "host2", "host3"],
          },
          {
            id: "vcenter-only",
            label: "Que vCenter este encendido",
            feedback: "No basta por si solo: el plano de gestion no demuestra capacidad, storage accesible ni politicas de recuperacion.",
            outcome: "unsafe",
            focusNodeIds: ["vcenter"],
          },
        ],
      },
    },
    {
      id: "recover",
      kind: "recover",
      title: "Define una recuperacion condicionada",
      instruction: "Explica que procedimiento aprobado seguiria el equipo y que cargas tendrian prioridad si la capacidad fuera limitada.",
      evidence: "host2/3 y vSAN representan los recursos que deben sostener el reinicio; la demo no ejecuta el runbook.",
      expected: "Selecciona una accion que preserve el control de capacidad y deje claro que debe autorizarse.",
      focusNodeIds: ["host2", "host3", "vsan"],
      sourceIds: ["vsphere-ha-restart", "vsphere-ha-capacity"],
      decision: {
        question: "Cual es la siguiente decision operativa mas segura para este modelo?",
        options: [
          {
            id: "validate-placement",
            label: "Validar capacidad y placement antes de confirmar los reinicios",
            feedback: "Mantiene separadas la intencion de HA y la evidencia real; permite priorizar cargas si el margen no alcanza.",
            outcome: "recommended",
            focusNodeIds: ["host2", "host3", "vsan"],
          },
          {
            id: "assume-vmotion",
            label: "Tratarlo como una migracion automatica sin mas comprobaciones",
            feedback: "Confunde dos mecanismos y oculta dependencias de capacidad, storage y politicas.",
            outcome: "unsafe",
            focusNodeIds: ["host1", "host2", "host3"],
          },
          {
            id: "force-restart",
            label: "Forzar reinicios sin revisar reservas ni prioridades",
            feedback: "Puede aumentar el impacto del incidente y no constituye un procedimiento aprobado por si mismo.",
            outcome: "unsafe",
            focusNodeIds: ["host2", "host3"],
          },
        ],
      },
    },
    {
      id: "validate",
      kind: "validate",
      title: "Valida servicio y proteccion",
      instruction: "Comprueba que las VMs prioritarias respondan y que el cluster conserve capacidad, storage y politicas para el siguiente evento.",
      evidence: "La recuperacion de un host no demuestra por si sola que cada aplicacion este funcional.",
      expected: "Cierra el escenario solo con evidencia de aplicacion, dependencias y margen operativo.",
      focusNodeIds: ["host2", "host3", "vsan"],
      sourceIds: ["vsphere-ha-capacity", "vsan-datastore"],
    },
  ],
  "multiple-host-failure": [
    {
      id: "observe",
      kind: "observe",
      title: "Mide el nuevo dominio de fallo",
      instruction: "Observa que dos hosts estan fuera y que el margen disponible para las cargas protegidas es menor.",
      evidence: "host1 y host2 aparecen afectados; host3 y vSAN son los recursos restantes de esta simplificacion.",
      expected: "Describe el cambio de capacidad sin prometer que todas las VMs continuaran disponibles.",
      focusNodeIds: ["host1", "host2", "host3"],
      sourceIds: ["vsphere-ha-capacity"],
    },
    {
      id: "diagnose",
      kind: "diagnose",
      title: "Calcula el margen antes de decidir",
      instruction: "Relaciona capacidad, reservas, prioridades y visibilidad del datastore antes de hablar de recuperacion.",
      evidence: "El escenario no calcula sizing; solo hace visible que el conjunto restante es menor.",
      expected: "Identifica que datos faltan para saber que cargas caben y cuales deben priorizarse.",
      focusNodeIds: ["host3", "vsan", "vcenter"],
      sourceIds: ["vsphere-ha-capacity", "vsphere-ha-restart", "vsan-datastore"],
      decision: {
        question: "Cual es la evidencia mas importante antes de afirmar que el resto de VMs se recuperara?",
        options: [
          {
            id: "remaining-capacity",
            label: "Capacidad, reservas y prioridades en los hosts restantes",
            feedback: "Permite contrastar la demanda con el margen real y decidir que cargas tienen prioridad.",
            outcome: "recommended",
            focusNodeIds: ["host3", "vsan"],
          },
          {
            id: "host-count",
            label: "Que quede al menos un host encendido",
            feedback: "El numero de hosts no expresa por si mismo CPU, memoria, storage, reservas ni politicas.",
            outcome: "incomplete",
            focusNodeIds: ["host3"],
          },
          {
            id: "management-green",
            label: "Que vCenter muestre estado verde",
            feedback: "La gestion aporta senales, pero no sustituye el calculo de capacidad ni la validacion de las cargas.",
            outcome: "incomplete",
            focusNodeIds: ["vcenter"],
          },
        ],
      },
    },
    {
      id: "recover",
      kind: "recover",
      title: "Prioriza la recuperacion",
      instruction: "Explica como se aplicaria un procedimiento de prioridad, reserva o reduccion controlada si el host restante no pudiera absorber toda la demanda.",
      evidence: "La animacion no decide que VMs son criticas ni modifica reservas o admission control.",
      expected: "Conecta la recuperacion con el plan de continuidad y con una decision aprobada por el cliente.",
      focusNodeIds: ["host3", "vsan"],
      sourceIds: ["vsphere-ha-capacity", "vsphere-ha-restart"],
      decision: {
        question: "Que respuesta mantiene una expectativa tecnicamente defendible?",
        options: [
          {
            id: "prioritize-workloads",
            label: "Priorizar cargas y validar capacidad antes de cada reinicio",
            feedback: "Reconoce que disponibilidad y capacidad son decisiones distintas y deja un criterio operativo explicito.",
            outcome: "recommended",
            focusNodeIds: ["host3", "vsan"],
          },
          {
            id: "all-workloads",
            label: "Afirmar que todas las VMs reiniciaran sin impacto",
            feedback: "No esta respaldado sin conocer demanda, reservas, politicas y capacidad restante.",
            outcome: "unsafe",
            focusNodeIds: ["host3"],
          },
          {
            id: "ignore-storage",
            label: "Revisar solo CPU y memoria e ignorar vSAN",
            feedback: "El storage accesible es una condicion del reinicio; omitirlo deja incompleta la hipotesis.",
            outcome: "unsafe",
            focusNodeIds: ["host3", "vsan"],
          },
        ],
      },
    },
    {
      id: "validate",
      kind: "validate",
      title: "Confirma que quedo protegido",
      instruction: "Valida las aplicaciones recuperadas, sus dependencias y el margen que queda para otro evento.",
      evidence: "Dos hosts fuera pueden dejar el cluster operativo pero con menor resiliencia y capacidad.",
      expected: "Documenta el resultado, las cargas no recuperadas y la accion necesaria para volver al nivel objetivo.",
      focusNodeIds: ["host3", "vsan", "vcenter"],
      sourceIds: ["vsphere-ha-capacity", "vsan-datastore"],
    },
  ],
  "management-plane-loss": [
    {
      id: "observe",
      kind: "observe",
      title: "Separa gestion y datos",
      instruction: "Observa la perdida de vCenter sin convertirla automaticamente en una caida de las VMs que ya estan ejecutandose.",
      evidence: "vCenter es el nodo afectado y las relaciones de storage de los hosts siguen representadas.",
      expected: "Explica que operacion de gestion queda afectada y que parte del camino de datos debe verificarse por separado.",
      focusNodeIds: ["vcenter", "host1", "host2", "host3"],
      sourceIds: ["vcf-platform", "vcf-91-faq"],
    },
    {
      id: "diagnose",
      kind: "diagnose",
      title: "Formula una hipotesis de impacto",
      instruction: "Distingue operaciones de inventario y control de la ejecucion de una VM, y lista las dependencias que deben comprobarse.",
      evidence: "La escena separa la arista de control de vCenter de las relaciones host-vSAN.",
      expected: "Evita afirmar que la gestion y el servicio son el mismo plano.",
      focusNodeIds: ["vcenter", "host1", "host2", "host3", "vsan"],
      sourceIds: ["vcf-platform", "vsphere-ha-restart", "vsan-datastore"],
      decision: {
        question: "Cual es la hipotesis inicial mas precisa ante la perdida de vCenter?",
        options: [
          {
            id: "management-impact",
            label: "Las operaciones de gestion estan afectadas; validar aparte el camino de datos",
            feedback: "Mantiene la separacion tecnica: no confunde la consola de gestion con la ejecucion de las cargas.",
            outcome: "recommended",
            focusNodeIds: ["vcenter", "host1", "host2", "host3"],
          },
          {
            id: "all-vms-down",
            label: "Todas las VMs estan caidas por definicion",
            feedback: "Es una conclusion absoluta que la escena no demuestra y que depende de la arquitectura real.",
            outcome: "unsafe",
            focusNodeIds: ["vcenter", "host1", "host2", "host3"],
          },
          {
            id: "no-impact",
            label: "No hay impacto porque los hosts siguen encendidos",
            feedback: "Tambien es incompleto: quedan afectadas operaciones, visibilidad y capacidad de administrar o recuperar.",
            outcome: "incomplete",
            focusNodeIds: ["vcenter"],
          },
        ],
      },
    },
    {
      id: "recover",
      kind: "recover",
      title: "Recupera el plano de gestion con control",
      instruction: "Define el procedimiento de restauracion de vCenter sin asumir que esa accion reemplaza la validacion del servicio.",
      evidence: "La simulacion no ejecuta una restauracion ni decide si las cargas necesitan una accion adicional.",
      expected: "Manten el alcance de la accion en gestion y deja explicitas las comprobaciones posteriores.",
      focusNodeIds: ["vcenter"],
      sourceIds: ["vcf-platform", "vcf-91-faq"],
      decision: {
        question: "Cual es la recuperacion mas responsable para este escenario conceptual?",
        options: [
          {
            id: "restore-management",
            label: "Restaurar vCenter segun el runbook y validar luego las cargas",
            feedback: "Acota la accion al plano afectado y conserva la validacion independiente del camino de datos.",
            outcome: "recommended",
            focusNodeIds: ["vcenter"],
          },
          {
            id: "restart-all-vms",
            label: "Reiniciar todas las VMs como respuesta inmediata",
            feedback: "Puede ampliar el impacto y no se justifica solo por perder la gestion.",
            outcome: "unsafe",
            focusNodeIds: ["host1", "host2", "host3", "vsan"],
          },
          {
            id: "ignore-management",
            label: "Ignorar vCenter mientras los hosts respondan",
            feedback: "Deja sin resolver operaciones, inventario, monitorizacion y procedimientos de recuperacion.",
            outcome: "incomplete",
            focusNodeIds: ["vcenter"],
          },
        ],
      },
    },
    {
      id: "validate",
      kind: "validate",
      title: "Valida ambos planos",
      instruction: "Comprueba la salud de vCenter y, por separado, el estado de las VMs, storage, red y operaciones pendientes.",
      evidence: "La recuperacion de la consola no certifica el servicio de las aplicaciones.",
      expected: "Cierra el incidente solo cuando la gestion y el servicio tengan evidencia suficiente.",
      focusNodeIds: ["vcenter", "host1", "host2", "host3", "vsan"],
      sourceIds: ["vcf-platform", "vsphere-ha-capacity", "vsan-datastore"],
    },
  ],
};
